# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: rootpasswordgiven
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: testlogin_app_development

test:
  <<: *default
  database: testlogin_app_test

production:
  <<: *default
  database: testlogin_app_production
  username: testlogin_app
  password: <%= ENV['TESTLOGIN_APP_DATABASE_PASSWORD'] %>
